### PR TITLE
Add a --random flag to render any random page

### PR DESCRIPTION
**Pull request by mycroft**
Basic random page rendering.

I know that is a pretty stupid PR/feature, but I'm using it daily to discover new stuff. Feel free to reject it is not acceptable.

Thanks!

### CODE REVIEW

**Review by spageektti — COMMENTED** [review]
Hi. Thanks for your contribution! If others agree, we could implement this in other clients as well.

**Comment by acuteenvy** [comment]
Thanks, but this is pretty easily achievable using `tldr --list` and other tools.
Try `tldr --list-all | shuf -n1 | xargs tldr`.

I'll wait for some other maintainers, but I honestly think things like that are better handled using shell pipelines and other commands.

**Comment by sbrl** [comment]
I don't see why its a problem to implement this here so long as it isn't incompatible with the client spec.

Different clients having special features isn't a problem I don't think.

I do also see @acuteenvy's point here. In this particular case you *can* do this with an external shell script. The question is whether there would be a benefit to integrate the feature into the main client vs asking people to rely on shell scripts. There's a fine balance to be had here.

What use-cases to you see for `--random`, @mycroft?

**Comment by mycroft** [comment]
Thanks for the feedback.

I've the feeling this PR is meeting some resistance, even by `rustfmt` or `clippy`, for this feature which, as everyone will agree, is not going to revolutionize the way this tool work. 

Therefore I'll close it. Thanks for your attention and happy new year nevertheless!

**Pull request closed without merging**
